In [1]:
import pandas as pd
import numpy as np
pd.__version__

'1.1.5'

In [2]:
pd.options.display.float_format = '{:,.2f}'.format

In [11]:
np.set_printoptions(precision=1)

In [12]:
x1 = np.random.rand(2,5) * 10 #Generacion de datos
x1

array([[3.2, 7.5, 7.7, 9.6, 2.4],
       [5.5, 9.4, 6.1, 4.6, 3.5]])

In [8]:
x2 = np.random.rand(2,5) * -1
x2

array([[-0.83, -0.35, -0.18, -0.1 , -0.96],
       [-0.32, -0.11, -0.25, -0.4 , -0.19]])

In [19]:
np.concatenate([x1,x2]) #Concatena ambas matrices, creando más filas; numpy

array([[ 3.2,  7.5,  7.7,  9.6,  2.4],
       [ 5.5,  9.4,  6.1,  4.6,  3.5],
       [-0.8, -0.3, -0.2, -0.1, -1. ],
       [-0.3, -0.1, -0.2, -0.4, -0.2]])

In [20]:
np.concatenate([x1,x2]).shape

(4, 5)

In [21]:
np.concatenate([x1,x2], axis = 1) #Se concatenan creandose mas columnas; numpy

array([[ 3.2,  7.5,  7.7,  9.6,  2.4, -0.8, -0.3, -0.2, -0.1, -1. ],
       [ 5.5,  9.4,  6.1,  4.6,  3.5, -0.3, -0.1, -0.2, -0.4, -0.2]])

In [22]:
np.concatenate([x1,x2], axis = 1).shape

(2, 10)

In [30]:
s1 = pd.Series(x1[0], index = ['a', 'b', 'c', 'd', 'e']) #Serie de datos con pandas
s1

a   3.20
b   7.55
c   7.74
d   9.61
e   2.37
dtype: float64

In [31]:
s2 = pd.Series(x2[0], index = ['c', 'd', 'e', 'f', 'g'])
s2

c   -0.83
d   -0.35
e   -0.18
f   -0.10
g   -0.96
dtype: float64

In [32]:
pd.concat([s1,s2]) #Se concatenan; pandas

a    3.20
b    7.55
c    7.74
d    9.61
e    2.37
c   -0.83
d   -0.35
e   -0.18
f   -0.10
g   -0.96
dtype: float64

In [34]:
pd.concat([s1,s2], axis = 1) #Se concatenan respetando los indices

0     1
a 3.20   nan
b 7.55   nan
c 7.74 -0.83
d 9.61 -0.35
e 2.37 -0.18
f  nan -0.10
g  nan -0.96

In [35]:
#Si no se requiere concatenar con base a los indices, conviene resetearlos
s1.reset_index(drop=True) #Sin la funcion drop quedará existiendo el indice como una columnas

0   3.20
1   7.55
2   7.74
3   9.61
4   2.37
dtype: float64

In [36]:
pd.concat([s1.reset_index(drop=True),s2.reset_index(drop=True)], axis = 1)

0     1
0 3.20 -0.83
1 7.55 -0.35
2 7.74 -0.18
3 9.61 -0.10
4 2.37 -0.96

In [37]:
df1 = pd.DataFrame(np.random.rand(3,2)*10, columns=['a', 'b'])
df1

a    b
0 6.12 1.91
1 8.83 5.07
2 1.77 1.92

In [38]:
df2 = pd.DataFrame(np.random.rand(3,2)*-1, columns=['a', 'b'], index = [2, 3, 4])
df2

a     b
2 -0.48 -0.81
3 -0.16 -0.86
4 -0.55 -0.61

In [41]:
pd.concat([df1, df2]) #Concatenar DataFrame, se repite un indice

a     b
0  6.12  1.91
1  8.83  5.07
2  1.77  1.92
2 -0.48 -0.81
3 -0.16 -0.86
4 -0.55 -0.61

In [43]:
pd.concat([df1, df2], axis = 1) #Se concatenan a lo largo de las columnas

a    b     a     b
0 6.12 1.91   nan   nan
1 8.83 5.07   nan   nan
2 1.77 1.92 -0.48 -0.81
3  nan  nan -0.16 -0.86
4  nan  nan -0.55 -0.61

In [45]:
pd.concat([df1, df2], axis = 1, join='inner') #Se concatenan los datos con indices compartidos

a    b     a     b
2 1.77 1.92 -0.48 -0.81

In [48]:
pd.concat([
           df1.reset_index(drop=True),
           df2.reset_index(drop=True)
           ], axis = 1) #Se resetean los indices para la concatenacion

a    b     a     b
0 6.12 1.91 -0.48 -0.81
1 8.83 5.07 -0.16 -0.86
2 1.77 1.92 -0.55 -0.61

In [50]:
df1.append(df2) #Otra forma de concatenar df

a     b
0  6.12  1.91
1  8.83  5.07
2  1.77  1.92
2 -0.48 -0.81
3 -0.16 -0.86
4 -0.55 -0.61

In [52]:
df1.append(df2).append(df2) #Concatenacion tras concatenacion

a     b
0  6.12  1.91
1  8.83  5.07
2  1.77  1.92
2 -0.48 -0.81
3 -0.16 -0.86
4 -0.55 -0.61
2 -0.48 -0.81
3 -0.16 -0.86
4 -0.55 -0.61

In [54]:
df1.T #Funcion de transpuesta

0    1    2
a 6.12 8.83 1.77
b 1.91 5.07 1.92

In [56]:
df1.T.append(df1.T).T

a    b    a    b
0 6.12 1.91 6.12 1.91
1 8.83 5.07 8.83 5.07
2 1.77 1.92 1.77 1.92