In [ ]:
10+3

13

In [ ]:
2*3

6

In [ ]:
2**3

8

In [ ]:
x = 12
x

12

In [ ]:
y = 15
x+y

27

In [ ]:
"Hola mundo"

'Hola mundo'

In [ ]:
x = "Hola"
y = "Mundo!"
x + " " + y

'Hola Mundo!'

In [ ]:
[1, 2, 3, 4, 5, 6]

[1, 2, 3, 4, 5, 6]

In [ ]:
[1, 2, 3, 4, 5, 6] + [1, 2, 3, 4, 5, 6]

[1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]

In [ ]:
lista = [1, 2, 3, 4, 5, 6]

In [ ]:
lista[0]

1

In [ ]:
lista[-1]

6

In [ ]:
import numpy as np


In [ ]:
np.array(lista)+10

array([11, 12, 13, 14, 15, 16])

In [ ]:
np.array([[1, 2, 3, 4], [5, 6, 7, 8]]).shape

(2, 4)

In [ ]:
otra_lista = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
lista_result = otra_lista[0]
lista_result*5

array([ 5, 10, 15, 20])

In [30]:
import pandas as pd

In [32]:
sr = pd.Series([10, 9, 8, 7, 6])
sr

0    10
1     9
2     8
3     7
4     6
dtype: int64

In [34]:
sr.values

array([10,  9,  8,  7,  6])

In [35]:
sr.index

RangeIndex(start=0, stop=5, step=1)

In [36]:
sr.shape

(5,)

In [37]:
sr[0]

10

In [38]:
sr[[0, 4, 2]]

0    10
4     6
2     8
dtype: int64

In [40]:
sr = pd.Series([10, 9, 8, 7, 6], index = ['a', 'b', 'c', 'd', 'e'])
sr

a    10
b     9
c     8
d     7
e     6
dtype: int64

In [44]:
Usuario = pd.Series(["Abisai", "Antonio Madera", 24, "México"], index=["Nombre", "Apellidos", "Edad", "País"])
Usuario

Nombre               Abisai
Apellidos    Antonio Madera
Edad                     24
País                 México
dtype: object

In [45]:
Usuario["Nombre"]

'Abisai'

In [46]:
dict_data = {'Co':100, 'Mx':200, 'Ar':300}
dict_data

{'Ar': 300, 'Co': 100, 'Mx': 200}

In [48]:
dict_data.keys()

dict_keys(['Co', 'Mx', 'Ar'])

In [49]:
dict_data['Ar']

300

In [50]:
pd.Series(dict_data)

Co    100
Mx    200
Ar    300
dtype: int64

In [51]:
import numpy as np

In [52]:
np.nan + 10

nan

In [54]:
sr = pd.Series(dict_data, ['Co', 'Mx', 'Pe'])
sr

Co    100.0
Mx    200.0
Pe      NaN
dtype: float64

In [56]:
sr.isnull()

Co    False
Mx    False
Pe     True
dtype: bool

In [57]:
sr.notnull()

Co     True
Mx     True
Pe    False
dtype: bool